'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class new_order
    
    '''<summary>
    '''btnSample control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSample As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''chkPartyCodePO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPartyCodePO As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Label270 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label270 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''MultiView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MultiView1 As Global.System.Web.UI.WebControls.MultiView
    
    '''<summary>
    '''View1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents View1 As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''Label344 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label344 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DropDownList24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownList24 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Label340 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label340 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DropDownList23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownList23 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Label345 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label345 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DropDownList25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownList25 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Button43 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button43 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Button44 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button44 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''View2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents View2 As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''Label341 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label341 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBox82 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox82 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Label342 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label342 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Delvdate6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Delvdate6 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Label346 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label346 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label5 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBox3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Label268 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label268 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Delvdate1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Delvdate1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Delvdate1_CalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Delvdate1_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''Label6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label6 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBox4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Label7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label7 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Delvdate2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Delvdate2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Delvdate2_CalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Delvdate2_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''Label220 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label220 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBox6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox6 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Label229 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label229 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Delvdate3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Delvdate3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Delvdate3_CalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Delvdate3_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''Label218 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label218 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBox54 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox54 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Label219 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label219 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBox55 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox55 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBox55_CalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox55_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''Label222 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label222 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBox56 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox56 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Label223 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label223 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBox57 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox57 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBox57_CalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox57_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''Label247 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label247 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBox8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox8 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Label248 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label248 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Delvdate4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Delvdate4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Label337 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label337 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DropDownList20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownList20 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Label212 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label212 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBox48 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox48 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Panel46 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel46 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Label230 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label230 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBox12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox12 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Label338 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label338 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBox81 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox81 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Panel47 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel47 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBox7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox7 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Label3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBox9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox9 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Label350 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label350 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Label250 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label250 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''payterm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents payterm As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Label253 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label253 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''paymode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents paymode As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Label267 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label267 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pay_agency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pay_agency As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Panel12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel12 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Label18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label18 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ldapplicable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ldapplicable As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Panel13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel13 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Label264 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label264 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''delvterm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents delvterm As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Label26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label26 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''despatch_mode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents despatch_mode As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Label251 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label251 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''destinatationTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents destinatationTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Panel15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel15 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Label252 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label252 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''freightterm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents freightterm As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Label271 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label271 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt_ITC_Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_ITC_Status As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Panel10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel10 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Label23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label23 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''insurance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents insurance As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Label24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label24 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''insupercent_TextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents insupercent_TextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''insurancetype control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents insurancetype As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Panel16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel16 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Label16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label16 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''misccharg_ComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents misccharg_ComboBox As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Label272 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label272 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''misc_tax_ComboBox4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents misc_tax_ComboBox4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Panel17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel17 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Label30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label30 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''inspeterm_ComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inspeterm_ComboBox As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Label282 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label282 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''third_party_insp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents third_party_insp As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Panel18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel18 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Label4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TextBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Label256 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label256 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''insp_test_ComboBox4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents insp_test_ComboBox4 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''insp_test_TextBox25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents insp_test_TextBox25 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Panel19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel19 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Label20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label20 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pvc_ComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pvc_ComboBox As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''pvc_TextBox26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pvc_TextBox26 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Panel20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel20 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Label19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label19 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''bonus_ComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bonus_ComboBox As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''bonus_TextBox27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bonus_TextBox27 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Panel21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel21 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Label257 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label257 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''performance_ComboBox0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents performance_ComboBox0 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''performance_TextBox28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents performance_TextBox28 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Panel22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel22 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Label258 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label258 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''per_gurrenty_ComboBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents per_gurrenty_ComboBox1 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''per_gurrenty_TextBox29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents per_gurrenty_TextBox29 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Panel23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel23 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Label259 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label259 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''sd_ComboBox2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sd_ComboBox2 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Label284 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label284 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''sd_TextBox46 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sd_TextBox46 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Label285 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label285 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Panel24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel24 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Label260 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label260 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''sp_gur_ComboBox3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sp_gur_ComboBox3 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''sp_gur_TextBox31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sp_gur_TextBox31 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Panel25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel25 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Label261 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label261 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''match_ComboBox2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents match_ComboBox2 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Panel26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel26 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Label22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label22 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''quantity_ComboBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents quantity_ComboBox As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Panel27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel27 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Label262 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label262 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''medicine_ComboBox0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents medicine_ComboBox0 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Panel28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel28 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''spl_del_Label263 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spl_del_Label263 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''spl_del_ComboBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spl_del_ComboBox1 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''spl_del_TextBox35 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spl_del_TextBox35 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Panel29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel29 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Label239 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label239 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''doc_sub_m_supl_TextBox49 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents doc_sub_m_supl_TextBox49 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Panel30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel30 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Label240 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label240 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''doc_bill_pay_TextBox50 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents doc_bill_pay_TextBox50 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Panel31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel31 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Label241 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label241 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''inv_party_TextBox51 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inv_party_TextBox51 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Label243 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label243 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''general_term_TextBox52 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents general_term_TextBox52 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Label244 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label244 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''note_TextBox53 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents note_TextBox53 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Button33 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button33 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Button32 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button32 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Label351 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label351 As Global.System.Web.UI.WebControls.Label
End Class
